// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import safeStorage from '../../lib/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://luafpyxqpfkvdjnmtbqh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_8uaCD--EKiwsaPj-Hg6toA_jH6El1Ir';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key) => safeStorage.getItem(key),
      setItem: (key, value) => safeStorage.setItem(key, value),
      removeItem: (key) => safeStorage.removeItem(key),
    },
    persistSession: true,
    autoRefreshToken: true,
  }
});